apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
        - name: ml-model
          image: ml-model:latest  # Replace with the correct image name if you're pushing to a registry
          ports:
            - containerPort: 5000
          env:
            - name: ENV_VAR_NAME
              value: "value"  # Add any environment variables if needed
